### ISSUE TITLE
模型转换代码

### ISSUE THREAD

**Issue by yotofu** [HorizonRDK/hobot_llm#1]
非常棒的工作！我想请教下你们将原始bloom模型转换至bpu推理模型是怎样一个流程，相关代码有没？

**Comment by zhuo511** [comment]
感谢认可，通过地平线工具链转换得到bpu推理模型，相关代码暂未开源。

**Comment by yotofu** [comment]
有开源计划没？自己根据工具链来研究转换复杂吗？我们的模型离落地就差你们这一步的开源啦~

**Comment by zhuo511** [comment]
您好，会有些复杂度，目前还在优化，暂时还没有明确的开源计划

**Comment by yotofu** [comment]
有没有测试过除了bloom其它类型的llm，比如llama等

**Comment by zhuo511** [comment]
目前没有
